docs_dir: .

# Project information
site_name: Satalign
site_url: https://ipl-uv.github.io/satalign/
site_author: IPL-UV Project
site_description: Satalign is a Python library for the alignment of satellite images using deep learning models.

# Repository
repo_url: https://github.com/IPL-UV/satalign
repo_name: satalign
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satalign.png
  favicon: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satalign.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide 

# Page tree
nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md

# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist

# Extra CSS
extra_css:
  - docs/style/style.css

# Extra JavaScript
extra_javascript:
  - docs/js/copybutton.js
