docs_dir: .

# Project information
site_name: Satalign
site_url: https://ipl-uv.github.io/satalign/
site_author: AndesDataCube Project
site_description: Satalign is a Python library for the alignment of satellite images using deep learning models.


# Repository
repo_url: https://github.com/IPL-UV/satalign
repo_name: satalign
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: black
      accent: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: https://huggingface.co/datasets/JulioContrerasH/DataMLSTAC/resolve/main/logo_satalign.png
  favicon: resources/ms_icon.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide 

# Page tree
nav:
  - Home: 
    - README.md
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md
    - Code of conduct: CODE_OF_CONDUCT.md
  # - Tasks: 
  #   - ./mlstac/collection/tasks/README.md
  #   - Remote Sensing:
  #     - Tensor Classification: ./mlstac/collection/tasks/TensorClassification.md
  #     - Tensor Regression: ./mlstac/collection/tasks/TensorRegression.md
  #     - Tensor Object Detection: ./mlstac/collection/tasks/TensorObjectDetection.md
  #     - Tensor Segmentation: ./mlstac/collection/tasks/TensorSegmentation.md
  #     - Tensor to Tensor: ./mlstac/collection/tasks/TensorToTensor.md
    
  #   - Multimodal:
  #     - Tensor to Text: ./mlstac/collection/tasks/TensorToText.md
  #     - Text to Tensor: ./mlstac/collection/tasks/TextToTensor.md
  # - Sample: 
  #   - ./mlstac/sample/README.md
  #   - Specification: ./mlstac/sample/specification.md
  #   - Safetensor: ./mlstac/sample/safetensor.md
  #   - Schema: ./mlstac/sample/squema.md
  # # - Catalog:
  # #   - ./mlstac/catalog/README.md
  # #   - Specification: ./mlstac/catalog/specification.md
  # #   - Squema: ./mlstac/catalog/squema.md
  # - Collection:
  #   - ./mlstac/collection/README.md
  #   - Specification: ./mlstac/collection/specification.md
  #   - Schema: ./mlstac/collection/squema.md
  # - API: ./mlstac/api/README.md

# Plugins
plugins:
  - search
  - same-dir
  - mkdocstrings 
  - awesome-pages

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist